"""add template drafts and fact provenance

Revision ID: e691a07c4161
Revises: 
Create Date: 2025-12-21 22:47:11.851318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e691a07c4161'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('relationships')
    op.drop_table('events')
    op.drop_table('template_drafts')
    op.drop_table('template_proposals')
    op.drop_table('users')
    op.drop_table('facts')
    op.drop_table('knowledge_edges')
    op.drop_table('session_entities')
    op.drop_table('entities')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('counterparty_style', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('attributes', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_entities',
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('attached_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'entity_id')
    )
    op.create_table('knowledge_edges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('knower_entity_id', sa.INTEGER(), nullable=False),
    sa.Column('fact_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=11), nullable=False),
    sa.Column('scope', sa.VARCHAR(length=13), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ),
    sa.ForeignKeyConstraint(['knower_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_entity_id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.VARCHAR(length=200), nullable=False),
    sa.Column('value_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('scope', sa.VARCHAR(length=13), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('provenance', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('tier', sa.VARCHAR(length=8), nullable=False),
    sa.Column('consent_telemetry', sa.BOOLEAN(), nullable=False),
    sa.Column('consent_raw_text', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_proposals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('draft_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('reviewer_notes', sa.TEXT(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['template_drafts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_drafts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('topic_text', sa.TEXT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=True),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=31), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('src_entity_id', sa.INTEGER(), nullable=False),
    sa.Column('rel_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dst_entity_id', sa.INTEGER(), nullable=False),
    sa.Column('provenance', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['dst_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['src_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'src_entity_id', 'rel_type', 'dst_entity_id', name=op.f('uix_relationship'))
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=12), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('llm_provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('llm_model', sa.VARCHAR(length=50), nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('token_usage', sa.INTEGER(), nullable=True),
    sa.Column('safety_flags', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
